In [19]:
import numpy as np
from scipy.optimize import linear_sum_assignment
import math 

def closest_pairs(inp1, inp2, threshold=np.inf):
    cost = np.zeros((inp1.shape[0], inp2.shape[0]), dtype=np.int64)

    for x in range(inp1.shape[0]):
        for y in range(inp2.shape[0]):
            cost[x][y] = abs(inp1[x] - inp2[y])
            #cost[x][y]=math.sqrt(abs(ts1[x]**2-ts2[y]**2))
            
    #print('matrix-cost')
    #print(cost)
    # cost for the above example:
    # [[16060 15820 14212 14273 38444]
    # [16121 15881 14151 14212 38383]
    # [17264 17024 13008 13069 37240]
    # [17384 17144 12888 12949 37120]
    # [24569 24329  5703  5764 29935]
    # [55794 55554 25522 25461  1290]
    # [55853 55613 25581 25520  1349]]

    # hungarian algorithm implementation provided by scipy
    row_ind, col_ind = linear_sum_assignment(cost)
    # row_ind = [0 1 3 4 5], col_ind = [1 0 3 2 4] 
    # where (ts1[5] - ts2[4]) = 1290

    # if you want the distances only
    out = [item 
           for item in cost[row_ind, col_ind] 
           if item < threshold]

    # if you want the pair of indices filtered by the threshold
    pairs = [(row, col) 
             for row, col in zip(row_ind, col_ind) 
             if cost[row, col] < threshold]
    
    
    t_cost=0
    for p in pairs:
        #print(p)
        t_cost=t_cost+cost[p]
     
    print(t_cost)
        
    return out, pairs


if __name__ == '__main__':
    ts1=np.array([ 1311242821.0, 1311242882.0, 1311244025.0, 1311244145.0, 1311251330.0, 1311282555.0, 1311282614.0])
    
    ts2=np.array([ 1311226761.0, 1311227001.0, 1311257033.0, 1311257094.0, 1311281265.0])
    
    ts1=np.array([ 1.0, 2.0, 5.0, 5.0, 4.0])
    
    ts2=np.array([ 1.0, 2.0, 5.0, 10.0, 4.0])
    
    
    

    #out, pairs = closest_pairs(ts1, ts2, 6000)
    #print(out, pairs)
    # out = [5703, 1290] 
    # pairs = [(4, 2), (5, 4)]

    out, pairs = closest_pairs(ts1, ts2)
    print(out, pairs)
    # out = [15820, 16121, 12949, 5703, 1290] 
    # pairs = [(0, 1), (1, 0), (3, 3), (4, 2), (5, 4)]
    
    
    

5
[0, 0, 5, 0, 0] [(0, 0), (1, 1), (2, 3), (3, 2), (4, 4)]
