In [1]:
def xcreatePadding(query, margin):
    #size=np.size(query)

    #b = np.insert(query, endX, values=255, axis=1)


    #create horizontal space
    w=query.shape[0]

    x=np.zeros(shape=(w, margin),dtype=int)
    x.fill(255)
    #x.astype(int)
    addLastCols = np.hstack((query, x))
    addFirstCols=np.hstack((x, addLastCols))
    newimg=addFirstCols

    #create vertical space
    h=newimg.shape[1]

    y=np.zeros(shape=(margin, h),dtype=int)
    y.fill(255)
    #y.astype(int)


    addBottomRows = np.vstack((newimg, y))
    addUpRows=np.vstack((y, addBottomRows))

    return addUpRows

def applyCircleErosion(word_img):
    colorvalue = [0, 0, 0]
    #enlarge_img= cv2.copyMakeBorder(word_img,10,10,10,10,cv2.BORDER_REPLICATE,value=colorvalue)
    
    #enlarge_img=createPadding(word_img, 10)
    kernel=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(9,9))
    erode_img = cv2.erode(word_img, kernel, iterations=1)
    #erode_img=enlarge_img
    return erode_img

In [6]:
import cv2 as cv2  
from matplotlib import pyplot as plt
import numpy as np


def createPadding(query, margin):
    #size=np.size(query)

    


    #create horizontal space
    w=query.shape[0]

    x=np.zeros(shape=(w, margin),dtype=int)
    x.fill(255)
    #x.astype(int)
    imgr = np.hstack((query, x))
    

    imgr = np.insert(query, endX, values=255, axis=1)

    imgr=query
    

    return imgr



query= cv2.imread("tmp1/kyrios4.png",0);
print(query)
print(query.shape)



img=query

img=createPadding(query, 20)

#print(img.shape)
#plt.figure()
#plt.imshow(img)

#print(img)


#img.astype(float)
kernel = np.ones((1,9), np.uint8)
#img = cv2.erode(source_img, kernel, iterations=1)
#kernel=cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(9,9))
img = cv2.erode(img, kernel, iterations=1)


plt.figure()
plt.imshow(img)






[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(45, 111)


NameError: name 'endX' is not defined