In [66]:
import numpy as np
import math 
from scipy.optimize import linear_sum_assignment
inp1 = np.array([1,2,3,4]) 
inp2 = np.array([12,13,14,15])
#inp2 = np.array([5,6,7])
#inp2 = np.array([14,15,6])

#a = np.array([[1,2,3]]) 
#a.mean()



#col=-1
#for row in a.T:
    #col=col+1
    #print(row)
    #print(a[col,col])

    
#@@@@@@@@@@@@@@@@@@@@ 



def closest_pairs(inp1, inp2, threshold=np.inf):

    cost = np.zeros((inp1.shape[0], inp2.shape[0]), dtype=np.float)   
    for x in range(inp1.shape[0]):
        for y in range(inp2.shape[0]):
            #cost[x][y] = abs(inp1[x] - inp2[y])
            cost[x][y]=math.sqrt((inp1[x]-inp2[y])**2+(x-y)**2) 

    #print(cost)
    col=-1
    sumdiagonal=0
    for row in cost.T:
        col=col+1
        #print(row)

        #print(cost[col,col])
        sumdiagonal=sumdiagonal+cost[col,col]

    translationCoef=sumdiagonal/(col+1)


    #print(sumdiagonal)   
    #print(translationCoef)   
    cost=abs(cost-translationCoef)

    threshold=100000

    row_ind, col_ind = linear_sum_assignment(cost)
    #print(row_ind)
    #print(col_ind)

    out = [item 
            for item in cost[row_ind, col_ind] 
            if item < threshold]

        # if you want the pair of indices filtered by the threshold
    pairs = [(row, col) 
             for row, col in zip(row_ind, col_ind) 
             if cost[row, col] < threshold]

    #print(pairs) 
    t_cost=0
    for p in pairs:
        #print(p)
        t_cost=t_cost+cost[p]

    print('total_cost',t_cost)

    return out, pairs


inp1 = np.array([1,2,3,4,8]) 
inp2 = np.array([1122,123,124,125])

closest_pairs(inp1, inp2, threshold=np.inf)

#@@@@@@@@@@@@@@@@@@@@   




print(cost)

total_cost 1489.9626314055472
[[0.         1.04159458 2.15294644 3.31782106]
 [0.95012438 0.         1.04159458 2.15294644]
 [1.78045554 0.95012438 0.         1.04159458]
 [2.45599625 1.78045554 0.95012438 0.        ]]


In [94]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

  
print(a) 
 
print('=========') 
# this returns array of items in the second column 
  
#print(a[...,1]  )
#print(a[1:,...])
print(a[1:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]]


In [87]:
import numpy as np 

a = np.array([[1,2,3,4,5],[1,2,3,4,5]]) 
np.savetxt('out.txt',a,delimiter=',') 
b = np.loadtxt('out.txt',delimiter=',') 
print( b)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


In [15]:
b = np.loadtxt('numtest.txt',delimiter=',') 
#print( b)


z=b[0,:]
print(z)

[ 0.      1.7373  3.9961  5.5333  6.9294  8.4039  9.898  13.439  17.125
 22.271  27.278  30.129  32.804  34.29   35.49   35.49   35.49   35.49
 35.49   35.49   32.718  25.431  19.376  14.945  12.365  11.671  11.325
 11.278  11.729  12.498  14.29   16.541  18.184  19.624  22.867  26.553
 29.522  32.38   33.973  35.467  36.247  36.984  36.984  36.914  36.239
 34.949  30.576  25.349  17.208  11.016   9.5843  9.1451 10.557  10.796
  9.3294 10.278  13.937  18.365  23.463  25.996  26.749  26.576  25.902
 25.129  24.314  23.027  21.604  20.106  18.608  15.867  12.988  11.42
  9.9333  9.9529  9.9059  9.149   8.5059  8.5059  8.651   9.4078  9.9686
  9.9686  9.9686  9.9686  9.9686  9.9686  9.6353  8.8824  9.2314 10.675
 11.357  11.451  14.18   18.502  20.918  22.427  23.369  24.106  24.851
 25.608  24.42   22.937  22.157  21.431  21.345  21.322  22.137  22.949
 23.616  24.161  24.141  23.957  23.216  21.22   16.118  11.765   8.8196
  6.502   5.1216  4.702   5.4     5.7255  5.7255  7.4118 10.263 